data:
  raw_data_path: "data/raw/IRIS.csv"
  processed_data_path: "data/processed/processed_dataset.csv"

model:
  type: "random_forest"
  hyperparameters:
    n_estimators: 100
    max_depth: 10